### ISSUE TITLE
BMP client should use http request instead of https

### ISSUE THREAD

**Issue by zhanggbj** [cloudfoundry-community/bosh-softlayer-tools#29]
BMP client should use http request,
http://{IP Address}:8080/info

In the softlayer-go http client, it is using https as below
https://github.com/maximilien/softlayer-go/blob/master/client/http_client.go#L95

**Comment by maximilien** [comment]
In `softlayer-go` you can change the `HttpClient`, see this unit test as [example](https://github.com/maximilien/softlayer-go/blob/master/client/softlayer_client_test.go#L44)

**Comment by maximilien** [comment]
Added fixes in [softlayer-go](https://github.com/maximilien/softlayer-go) to allow HTTP scheme to be settable
