### ISSUE TITLE
remove table output from unit tests

### ISSUE THREAD

**Issue by maximilien** [cloudfoundry-community/bosh-softlayer-tools#45]
Currently unit tests runs polute the terminal output with table headers and some other output, e.g.,:

```
------------------------------
+----------+
| STEMCELL |
+----------+
+----------+
Stemcells total:  0

•••••••••••••
------------------------------
Login Successful!

•••
------------------------------
Login Successful!

•••••••••••
```

Need to get rid of all output. Set all UT to `VERBOSE=false`

**Comment by zhanggbj** [comment]
In command Execute method, I used cmd.ui.PrintlnInfo to print these information and it won't check VERBOSE like cmd.ui.Println do, so that these messages will always show up without using --verbose in command line. And when executing UT,  these messages will also show up.

Did I missed something when we talked about this in last scrum?

**Comment by maximilien** [comment]
So I would like to have a environment variable called `UT_OUTPUT` that is `false` by default. When `true` then output is shown during UT execution, otherwise all output is suppressed. So when running UTs and we need output we can turn it on, otherwise no output. All `Ui` methods should check this env to decide to show output or not, regardless or `verbose`. That's a UT-specific env and it overrides everything, but it's meant just for tests. Cool?

**Comment by zhanggbj** [comment]
Sorry I just noticed your last comment after code submitted. I updated UI output in a similar way, is this work for you? Thanks!

**Comment by maximilien** [comment]
Last PR seems to have removed a lot but problem still there. I still see some, e.g.,:

```
➜  bosh-softlayer-tools git:(master) bin/test-unit

 Cleaning build artifacts...

 Formatting packages...

 Unit Testing packages:
Will skip:
  ./integration
  ./integration/bmp
  ./integration/stemcells
[1463709819] Clients Suite - 21/21 specs - 4 nodes ••••••••••••••••••••• SUCCESS! 35.562999ms
[1463709819] Cmds Suite - 4/4 specs - 4 nodes •••• SUCCESS! 25.834851ms
[1463709819] Bmp Suite - 102/102 specs - 4 nodes •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••• SUCCESS! 241.32251ms
[1463709819] Import Image Suite - 6/6 specs - 4 nodes •••••• SUCCESS! 21.686752ms
[1463709819] Light Stemcell Suite - 24/24 specs - 4 nodes •••••••••••••••••••••••• SUCCESS! 75.414416ms
[1463709819] Common Suite - 13/13 specs - 4 nodes ••
------------------------------
in fakeUI PrintfInfo
••••
------------------------------
in fakeUI PrintfInfo
••••••• SUCCESS! 32.003776ms
[1463709819] Config Suite - 6/6 specs - 4 nodes •••••• SUCCESS! 28.233557ms
[1463709819] Main Suite - 0/0 specs - 4 nodes  SUCCESS! 16.170242ms

Ginkgo ran 8 suites in 13.332323701s
Test Suite Passed

 Vetting packages for potential issues...

SWEET SUITE SUCCESS
```

**Comment by zhanggbj** [comment]
Sorry that's a debug info. I removed this line in PR #60 . Thank you.

**Comment by zhanggbj** [comment]
Code merged. This is fixed.
