### ISSUE TITLE
Please add 2 repositories into Godeps

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry-community/bosh-softlayer-tools#52]
@maximilien Please add the following 2 repositories into Godeps, it's a dependency to the merge work from Kara's repo to this repo. Thanks.

```
github.com/maximilien/softlayer-go/softlayer
github.com/pivotal-golang/clock
```

**Comment by maximilien** [comment]
Submit these two as a separate Godeps update PR and I'll merge

**Comment by zhanggbj** [comment]
@maximilien @mattcui 
Updated godeps in PR #58. Thanks.

**Comment by mattcui** [comment]
@maximilien Please help merge this PR when you get time, it's a dependency to another important PR about publishing public image pipeline.

**Comment by maximilien** [comment]
Done.
